Repository optmzr/camomile, pull requests merged in 2019-09, with the labels that each got.

#27 ci: set Go 1.13
  .circleci/config.yml
Labels: enhancement

#19 Construct initial CLI
  cmd/dhtctl/main.go
Labels: enhancement

#38 doc: update README.md with badges and new name
  README.md
Labels: documentation, enhancement

#55 dht+network+node: node.(ID).Bytes() must return a copy of bytes
  dht/dht.go
  network/network.go
  node/node.go
Labels: bug

#56 get now responds with sender
  cmd/dhtctl/main.go
  ctl/ctl.go
  dht/call.go
  dht/dht.go
  dht/dht_test.go
Labels: PANIC ATTACK!!!!!!!!!!!!!1, ULTRA URGENT!!!, Urgent

#57 dht: limit to a maximum of k nodes when storing
  dht/dht.go
Labels: bug
