Repository optmzr/camomile, pull requests merged in 2019-10, with the labels that each got.

#63 network+misc: add network timeouts and fast logging
  bin/get-from-random.sh
  bin/put-to-random.sh
  bin/run-cluster.sh
  bin/run-node.sh
  cmd/dhtnode/main.go
  ctl/ctl.go
  dht/dht.go
  example/network-channels/main.go
  go.mod
  go.sum
  network/network.go
  network/network_test.go
  network/table.go
  network/table_test.go
  packet/packet.proto
  packet/packet_test.go
  route/contact.go
  route/table.go
  route/table_test.go
  store/store.go
Labels: Advanced, BORDERLINE isSuE, CRUCIAL, Complex, Expert, Good to have, PANIC ATTACK!!!!!!!!!!!!!1, ULTRA URGENT!!!, Urgent, VERY HARD, bug, enhancement, testing

#68 network+bin: fix session timeouts and use super node instead
  bin/do-random.sh
  bin/run-cluster.sh
  network/network.go
  network/table.go
Labels: bug

#71 cmd/dhtnode: RESTful API
  README.md
  cmd/dhtnode/http.go
  cmd/dhtnode/main.go
  cmd/dhtnode/rpc.go
Labels: 🏆 QUALIFYING 🏆

#73 cmd/dhtnode+doc: follow lab spec (almost) and update docs
  README.md
  cmd/dhtnode/http.go
Labels: bug

#67 Add forgetLocalItem and forgetItem test
  cmd/dhtctl/main.go
  ctl/ctl.go
  dht/call.go
  dht/dht.go
  dht/dht_test.go
  store/store.go
  store/store_test.go
Labels: enhancement, 🏆 QUALIFYING 🏆

#79 update tExpire upon value request (getItem)
  store/store.go
Labels: bug, enhancement, in progress

#77 connect-replication-channel-to-dht
  dht/dht.go
  dht/handler.go
  store/store.go
  store/store_test.go
Labels: BORDERLINE isSuE

#81 uml visualizations
  .gitattributes
  camomile.svg
  example/bucket.go
  example/contact.go
  example/docker-compose-lab.yml
  example/kademlia.go
  example/kademliaid.go
  example/network-channels/main.go
  example/network.go
  example/routingtable.go
  example/routingtable_test.go
  example/walk-call-pattern/main.go
  packet_pb2.png
Labels: enhancement

#85 remove udptestclient
  cmd/udptestclient/udptestclient.go
Labels: enhancement

#82 doc: add FAQ about ARP table overflow
  README.md
Labels: documentation
